services:
  # ==========================
  # 🗄️ MySQL Database
  # ==========================
  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # ==========================
  # 🧰 phpMyAdmin
  # ==========================
  dbviewer:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: toor
      UPLOAD_LIMIT: 64M
    ports:
      - "8080:80"
    depends_on:
      - db

  # ==========================
  # 🖥️ Portainer
  # ==========================
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

# ==========================
# 🧱 Volumes
# ==========================
volumes:
  mysql_data:
  portainer_data:
